# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stadia_EM_SP <- function(x, position, batch_vec, adj_mat_mnn, hyper, init, platform, d = 15L, K = 7L, adj_cutoff = 50., icm_maxiter = 10L, em_maxiter = 5L, verbose = TRUE, verbose_icm = FALSE, ncores = 4L) {
    .Call(`_stadia_stadia_EM_SP`, x, position, batch_vec, adj_mat_mnn, hyper, init, platform, d, K, adj_cutoff, icm_maxiter, em_maxiter, verbose, verbose_icm, ncores)
}

calAdjacent <- function(position_, batch_vec_, platform, cutoff = 50, ncores = 4L) {
    .Call(`_stadia_calAdjacent`, position_, batch_vec_, platform, cutoff, ncores)
}

convertSparse <- function(mat) {
    .Call(`_stadia_convertSparse`, mat)
}

update_c_sp <- function(x, adj_mat, c_vec, B, L, Mu, T, Lambda, batch_vec, omega_vec, eta_vec, icm_maxiter = 10L, verbose = TRUE, ncores = 4L) {
    .Call(`_stadia_update_c_sp`, x, adj_mat, c_vec, B, L, Mu, T, Lambda, batch_vec, omega_vec, eta_vec, icm_maxiter, verbose, ncores)
}

update_c_sc <- function(x, B, L, Mu, T, Lambda, batch_vec, omega_vec, pk_mat, ncores = 4L) {
    .Call(`_stadia_update_c_sc`, x, B, L, Mu, T, Lambda, batch_vec, omega_vec, pk_mat, ncores)
}

expect_f <- function(x, inv_Phis_list, B, Lambda, Mu, T, L, S_lik, omega_vec, batch_vec, ncores) {
    .Call(`_stadia_expect_f`, x, inv_Phis_list, B, Lambda, Mu, T, L, S_lik, omega_vec, batch_vec, ncores)
}

expect_gamma <- function(L, lambda0, lambda1, p_vec, ncores) {
    .Call(`_stadia_expect_gamma`, L, lambda0, lambda1, p_vec, ncores)
}

update_T <- function(x, B, L, Efft_li, Ef_li, batch_vec, nu_tau, ncores) {
    .Call(`_stadia_update_T`, x, B, L, Efft_li, Ef_li, batch_vec, nu_tau, ncores)
}

update_B <- function(x, T, L, Ef_li, batch_vec, n_b, ncores) {
    .Call(`_stadia_update_B`, x, T, L, Ef_li, batch_vec, n_b, ncores)
}

update_mu <- function(S_lik, Lambda, mu_mu, sigma_mu, Ef_k, omega_vec, ncores) {
    .Call(`_stadia_update_mu`, S_lik, Lambda, mu_mu, sigma_mu, Ef_k, omega_vec, ncores)
}

update_omega <- function(S_lik, Mu, Lambda, Efft_li, weightEf_liks, nu_omega, ncores) {
    .Call(`_stadia_update_omega`, S_lik, Mu, Lambda, Efft_li, weightEf_liks, nu_omega, ncores)
}

update_Lambda <- function(Efft_li, muEf, omega_vec, S_lik, Mu, n_Lambda, Sigma_Lambda, ncores) {
    .Call(`_stadia_update_Lambda`, Efft_li, muEf, omega_vec, S_lik, Mu, n_Lambda, Sigma_Lambda, ncores)
}

update_p <- function(Egamma, alpha_p, beta_p, ncores) {
    .Call(`_stadia_update_p`, Egamma, alpha_p, beta_p, ncores)
}

update_L <- function(x, B, Egamma, batch_vec, Ef_li, Efft_li, T, L, lambda0, lambda1, ncores) {
    .Call(`_stadia_update_L`, x, B, Egamma, batch_vec, Ef_li, Efft_li, T, L, lambda0, lambda1, ncores)
}

logPrior_L <- function(L, p_vec, lambda0, lambda1) {
    .Call(`_stadia_logPrior_L`, L, p_vec, lambda0, lambda1)
}

logPrior_B <- function(B) {
    .Call(`_stadia_logPrior_B`, B)
}

logPrior_mu <- function(mu, mu_mu, Sigma_mu) {
    .Call(`_stadia_logPrior_mu`, mu, mu_mu, Sigma_mu)
}

logPrior_omega <- function(omega_vec, nu_omega) {
    .Call(`_stadia_logPrior_omega`, omega_vec, nu_omega)
}

logPrior_T <- function(T, nu_tau) {
    .Call(`_stadia_logPrior_T`, T, nu_tau)
}

logPrior_Lambda <- function(Lambda, n_Lambda, Sigma_Lambda) {
    .Call(`_stadia_logPrior_Lambda`, Lambda, n_Lambda, Sigma_Lambda)
}

logPrior_p <- function(p_vec, alpha_p, beta_p) {
    .Call(`_stadia_logPrior_p`, p_vec, alpha_p, beta_p)
}

logPost <- function(loglik, L, B, mu, p_vec, omega_vec, T, Lambda, lambda0, lambda1, mu_mu, Sigma_mu, nu_omega, nu_tau, n_Lambda, Sigma_Lambda, alpha_p, beta_p) {
    .Call(`_stadia_logPost`, loglik, L, B, mu, p_vec, omega_vec, T, Lambda, lambda0, lambda1, mu_mu, Sigma_mu, nu_omega, nu_tau, n_Lambda, Sigma_Lambda, alpha_p, beta_p)
}

calPhi <- function(T, L, Lambda, omega_vec, batch_vec) {
    .Call(`_stadia_calPhi`, T, L, Lambda, omega_vec, batch_vec)
}

calEnergy_latent <- function(adj_mat, c_vec, K, eta_vec, batch_vec) {
    .Call(`_stadia_calEnergy_latent`, adj_mat, c_vec, K, eta_vec, batch_vec)
}

calEnergy_observed <- function(x, B, L, Mu, T, Lambda, batch_vec, omega_vec, ncores = 4L) {
    .Call(`_stadia_calEnergy_observed`, x, B, L, Mu, T, Lambda, batch_vec, omega_vec, ncores)
}

